[package]
name = "bansheelong_storage_server"
version = "0.1.0"
edition = "2021"

[dependencies]
bansheelong_types = { path = "../types" }
futures = "0.3.21"
tokio = { features = ["full"], version = "1.20.1" }
